watch_stylesheet: true
watch_config: true
debug: false

bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: "#11111b"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 4
      left: 10
      bottom: 4
      right: 10
    widgets:
      left: ["win_button","active_window"]
      center: ["clock"]
      right: ["update","weather","volume","language","power_menu"]

widgets:
  # Left widgets
  win_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\ue62a"
        label_alt: "\ue62a"
        class_name: "system-widget"
        callbacks:
          on_left: "exec cmd.exe /c start %LOCALAPPDATA%\\FlowLauncher\\Flow.Launcher.exe"
  active_window:
      type: "yasb.active_window.ActiveWindowWidget"
      options:
        label: "{win[title]}"
        label_alt: ""
        label_no_window: ""
        label_icon: false
        label_icon_size: 12
        max_length: 36
        max_length_ellipsis: "..."
        monitor_exclusive: true

  # Center widgets
  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%A, %B %d, %Y | %H:%M:%S}"
        label_alt: "{%A, %B %d, %Y | %H:%M:%S}"
        timezones: [] #Looking up time zone info from registry

  # Right widgets
  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf019</span> {count}"
        interval: 1800
        exclude: []
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span> {count}"
        interval: 240
        exclude: []
  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {temp_c}째C"
        label_alt: "{location}: {conditions} | Temp: {temp_c}째C ({min_temp_c}째C - {max_temp_c}째C)"
        api_key: '3bf4cf9a7c3f40d6b31174128242807'
        update_interval: 900
        hide_decimal: true
        location: 'Nakhon Pathom, Nakhon Pathom'
        callbacks:
          on_left: "toggle_label"
          on_right: "exec cmd.exe /c start https://www.weatherapi.com/weather/q/nakhon-pathom-nakhon-pathom-thailand"
        icons: 
          sunnyDay: "\ue30d"
          clearNight: "\ue32b"
          cloudyDay: "\ue312"
          cloudyNight: "\ue312"
          rainyDay: "\ue308"
          rainyNight: "\ue308"
          snowyIcyDay: "\ue31a"
          snowyIcyNight: "\ue31a"
          default: "\ue302"
  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span> {level}"
        label_alt: "{volume}"
        volume_icons:
          - "\ueee8"  # Icon for muted
          - "\uf026"  # Icon for 0-10% volume
          - "\uf027"  # Icon for 11-30% volume
          - "\uf027"  # Icon for 31-60% volume
          - "\uf028"  # Icon for 61-100% volume
        callbacks:
          on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 250 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          shutdown: ["\uf011", "Shut Down"]
          restart: ["\uead2", "Restart"]
          signout: ["\udb80\udf43", "Sign out"]
          hibernate: ["\uf28e", "Hibernate"]
          sleep: ["\u23fe", "Sleep"]
          cancel: ["", "Cancel"]

  language:
      type: "yasb.language.LanguageWidget"
      options:
        label: "\uf0ac {lang[language_code]}"
        label_alt: "\uf0ac {lang[full_name]}"
        update_interval: 1